# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt5gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RadioTelescope(object):
    def setupUi(self, RadioTelescope):
        RadioTelescope.setObjectName("RadioTelescope")
        RadioTelescope.resize(1187, 829)
        RadioTelescope.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(RadioTelescope)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioSignal = QtWidgets.QWidget(self.centralwidget)
        self.radioSignal.setMinimumSize(QtCore.QSize(0, 300))
        self.radioSignal.setObjectName("radioSignal")
        self.verticalLayout.addWidget(self.radioSignal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoBox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBox.sizePolicy().hasHeightForWidth())
        self.infoBox.setSizePolicy(sizePolicy)
        self.infoBox.setObjectName("infoBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.infoBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.telescopeInfo = QtWidgets.QListWidget(self.infoBox)
        self.telescopeInfo.setObjectName("telescopeInfo")
        self.verticalLayout_4.addWidget(self.telescopeInfo)
        self.horizontalLayout.addWidget(self.infoBox)
        self.allSkyMap = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allSkyMap.sizePolicy().hasHeightForWidth())
        self.allSkyMap.setSizePolicy(sizePolicy)
        self.allSkyMap.setObjectName("allSkyMap")
        self.horizontalLayout.addWidget(self.allSkyMap)
        self.commandBox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandBox.sizePolicy().hasHeightForWidth())
        self.commandBox.setSizePolicy(sizePolicy)
        self.commandBox.setMaximumSize(QtCore.QSize(16777215, 600))
        self.commandBox.setObjectName("commandBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.commandBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ra = QtWidgets.QLineEdit(self.commandBox)
        self.ra.setObjectName("ra")
        self.horizontalLayout_2.addWidget(self.ra)
        self.dec = QtWidgets.QLineEdit(self.commandBox)
        self.dec.setObjectName("dec")
        self.horizontalLayout_2.addWidget(self.dec)
        self.slewBtn = QtWidgets.QPushButton(self.commandBox)
        self.slewBtn.setObjectName("slewBtn")
        self.horizontalLayout_2.addWidget(self.slewBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.trackBtn = QtWidgets.QCheckBox(self.commandBox)
        self.trackBtn.setObjectName("trackBtn")
        self.horizontalLayout_3.addWidget(self.trackBtn)
        self.recordBtn = QtWidgets.QCheckBox(self.commandBox)
        self.recordBtn.setObjectName("recordBtn")
        self.horizontalLayout_3.addWidget(self.recordBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.parkBtn = QtWidgets.QPushButton(self.commandBox)
        self.parkBtn.setObjectName("parkBtn")
        self.horizontalLayout_3.addWidget(self.parkBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.commandOutput = QtWidgets.QListWidget(self.commandBox)
        self.commandOutput.setObjectName("commandOutput")
        self.verticalLayout_3.addWidget(self.commandOutput)
        self.horizontalLayout.addWidget(self.commandBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        RadioTelescope.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(RadioTelescope)
        self.statusBar.setObjectName("statusBar")
        RadioTelescope.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(RadioTelescope)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(RadioTelescope)
        QtCore.QMetaObject.connectSlotsByName(RadioTelescope)

    def retranslateUi(self, RadioTelescope):
        _translate = QtCore.QCoreApplication.translate
        RadioTelescope.setWindowTitle(_translate("RadioTelescope", "MainWindow"))
        self.slewBtn.setText(_translate("RadioTelescope", "Slew"))
        self.trackBtn.setText(_translate("RadioTelescope", "Track"))
        self.recordBtn.setText(_translate("RadioTelescope", "Record"))
        self.parkBtn.setText(_translate("RadioTelescope", "Park"))
        self.actionAbout.setText(_translate("RadioTelescope", "About"))

