# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt5gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RadioTelescope(object):
    def setupUi(self, RadioTelescope):
        RadioTelescope.setObjectName("RadioTelescope")
        RadioTelescope.resize(1138, 819)
        RadioTelescope.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(RadioTelescope)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioSignal = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioSignal.sizePolicy().hasHeightForWidth())
        self.radioSignal.setSizePolicy(sizePolicy)
        self.radioSignal.setMinimumSize(QtCore.QSize(0, 300))
        self.radioSignal.setObjectName("radioSignal")
        self.verticalLayout.addWidget(self.radioSignal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoBox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBox.sizePolicy().hasHeightForWidth())
        self.infoBox.setSizePolicy(sizePolicy)
        self.infoBox.setObjectName("infoBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.infoBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.telescopeInfo = QtWidgets.QTableWidget(self.infoBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telescopeInfo.sizePolicy().hasHeightForWidth())
        self.telescopeInfo.setSizePolicy(sizePolicy)
        self.telescopeInfo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.telescopeInfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.telescopeInfo.setAlternatingRowColors(True)
        self.telescopeInfo.setShowGrid(False)
        self.telescopeInfo.setGridStyle(QtCore.Qt.DotLine)
        self.telescopeInfo.setRowCount(12)
        self.telescopeInfo.setColumnCount(2)
        self.telescopeInfo.setObjectName("telescopeInfo")
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.telescopeInfo.setItem(11, 0, item)
        self.telescopeInfo.horizontalHeader().setVisible(False)
        self.telescopeInfo.horizontalHeader().setDefaultSectionSize(130)
        self.telescopeInfo.horizontalHeader().setStretchLastSection(True)
        self.telescopeInfo.verticalHeader().setVisible(False)
        self.telescopeInfo.verticalHeader().setHighlightSections(True)
        self.verticalLayout_4.addWidget(self.telescopeInfo)
        self.horizontalLayout.addWidget(self.infoBox)
        self.allSkyMap = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allSkyMap.sizePolicy().hasHeightForWidth())
        self.allSkyMap.setSizePolicy(sizePolicy)
        self.allSkyMap.setMinimumSize(QtCore.QSize(400, 400))
        self.allSkyMap.setObjectName("allSkyMap")
        self.figvl = QtWidgets.QVBoxLayout(self.allSkyMap)
        self.figvl.setObjectName("figvl")
        self.horizontalLayout.addWidget(self.allSkyMap)
        self.commandBox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandBox.sizePolicy().hasHeightForWidth())
        self.commandBox.setSizePolicy(sizePolicy)
        self.commandBox.setMaximumSize(QtCore.QSize(16777215, 600))
        self.commandBox.setObjectName("commandBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.commandBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ra = QtWidgets.QLineEdit(self.commandBox)
        self.ra.setObjectName("ra")
        self.horizontalLayout_2.addWidget(self.ra)
        self.dec = QtWidgets.QLineEdit(self.commandBox)
        self.dec.setObjectName("dec")
        self.horizontalLayout_2.addWidget(self.dec)
        self.trackBtn = QtWidgets.QCheckBox(self.commandBox)
        self.trackBtn.setMinimumSize(QtCore.QSize(67, 0))
        self.trackBtn.setBaseSize(QtCore.QSize(0, 0))
        self.trackBtn.setObjectName("trackBtn")
        self.horizontalLayout_2.addWidget(self.trackBtn)
        self.slewBtn = QtWidgets.QPushButton(self.commandBox)
        self.slewBtn.setObjectName("slewBtn")
        self.horizontalLayout_2.addWidget(self.slewBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recordPath = QtWidgets.QLineEdit(self.commandBox)
        self.recordPath.setObjectName("recordPath")
        self.horizontalLayout_3.addWidget(self.recordPath)
        self.recordBtn = QtWidgets.QCheckBox(self.commandBox)
        self.recordBtn.setMinimumSize(QtCore.QSize(67, 0))
        self.recordBtn.setBaseSize(QtCore.QSize(0, 0))
        self.recordBtn.setObjectName("recordBtn")
        self.horizontalLayout_3.addWidget(self.recordBtn)
        self.parkBtn = QtWidgets.QPushButton(self.commandBox)
        self.parkBtn.setObjectName("parkBtn")
        self.horizontalLayout_3.addWidget(self.parkBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.commandOutput = QtWidgets.QListWidget(self.commandBox)
        self.commandOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.commandOutput.setAutoScrollMargin(0)
        self.commandOutput.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.commandOutput.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.commandOutput.setObjectName("commandOutput")
        self.verticalLayout_3.addWidget(self.commandOutput)
        self.horizontalLayout.addWidget(self.commandBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        RadioTelescope.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(RadioTelescope)
        self.statusBar.setObjectName("statusBar")
        RadioTelescope.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(RadioTelescope)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(RadioTelescope)
        QtCore.QMetaObject.connectSlotsByName(RadioTelescope)

    def retranslateUi(self, RadioTelescope):
        _translate = QtCore.QCoreApplication.translate
        RadioTelescope.setWindowTitle(_translate("RadioTelescope", "MainWindow"))
        self.telescopeInfo.setSortingEnabled(False)
        __sortingEnabled = self.telescopeInfo.isSortingEnabled()
        self.telescopeInfo.setSortingEnabled(False)
        item = self.telescopeInfo.item(0, 0)
        item.setText(_translate("RadioTelescope", "Location"))
        item = self.telescopeInfo.item(1, 0)
        item.setText(_translate("RadioTelescope", "Latitude"))
        item = self.telescopeInfo.item(2, 0)
        item.setText(_translate("RadioTelescope", "Longitude"))
        item = self.telescopeInfo.item(3, 0)
        item.setText(_translate("RadioTelescope", "Elevation"))
        item = self.telescopeInfo.item(4, 0)
        item.setText(_translate("RadioTelescope", "Date"))
        item = self.telescopeInfo.item(5, 0)
        item.setText(_translate("RadioTelescope", "JD"))
        item = self.telescopeInfo.item(6, 0)
        item.setText(_translate("RadioTelescope", "Time (UT)"))
        item = self.telescopeInfo.item(7, 0)
        item.setText(_translate("RadioTelescope", "Recording filepath"))
        item = self.telescopeInfo.item(8, 0)
        item.setText(_translate("RadioTelescope", "Right Ascension"))
        item = self.telescopeInfo.item(9, 0)
        item.setText(_translate("RadioTelescope", "Declination"))
        item = self.telescopeInfo.item(10, 0)
        item.setText(_translate("RadioTelescope", "Altitude"))
        item = self.telescopeInfo.item(11, 0)
        item.setText(_translate("RadioTelescope", "Azimuth"))
        self.telescopeInfo.setSortingEnabled(__sortingEnabled)
        self.trackBtn.setText(_translate("RadioTelescope", "Track"))
        self.slewBtn.setText(_translate("RadioTelescope", "Slew"))
        self.recordBtn.setText(_translate("RadioTelescope", "Record"))
        self.parkBtn.setText(_translate("RadioTelescope", "Park"))
        self.actionAbout.setText(_translate("RadioTelescope", "About"))

